export const GET_SEARCH_RESULT_REQUEST = 'GET_SEARCH_RESULT_REQUEST';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAIL = 'GET_SEARCH_RESULT_FAIL';


export const GET_RETRIEVE_RESULT_REQUEST = 'GET_RETRIEVE_RESULT_REQUEST';
export const GET_RETRIEVE_RESULT_SUCCESS = 'GET_RETRIEVE_RESULT_SUCCESS';
export const GET_RETRIEVE_RESULT_FAIL = 'GET_RETRIEVE_RESULT_FAIL';